#!/usr/bin/zsh

# XDG (PREFIX only used for termux compatibily)
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# Start the xsession IF xmonad is there and we are in tty1.
if [ "$(tty)" = "/dev/tty1" ] && [ -n "$(command -v xmonad)" ]; then
  pgrep xmonad || startx
fi
